### ISSUE TITLE
A better how to compile guide.

### ISSUE THREAD

**Issue by BoBeR182** [BansheeMediaPlayer/banshee-community-extensions#1]
~/banshee-community-extensions$ ./autogen.sh 
Error: intltoolize is not installed, and is required to configure

**Comment by BoBeR182** [comment]
After sudo apt-get install intltool

~/banshee-community-extensions$ ./autogen.sh 
Running intltoolize --force --copy ...
You should add the contents of '/usr/share/aclocal/intltool.m4' to 'aclocal.m4'.
Running libtoolize --force --copy --automake ...
Running aclocal -I build/m4 -I build/m4/shamrock -I build/m4/shave -I build/m4/extensions ...
Running autoconf ...
configure.ac:51: error: possibly undefined macro: AM_GCONF_SOURCE_2
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
Error: Could not run autoconf, which is required to configure banshee-community-extensions

**Comment by BoBeR182** [comment]
~/banshee-community-extensions$ ./autogen.sh 
Running intltoolize --force --copy ...
Running libtoolize --force --copy --automake ...
Running aclocal -I build/m4 -I build/m4/shamrock -I build/m4/shave -I build/m4/extensions ...
Running autoconf ...
Running autoheader ...
Running automake --gnu --add-missing --force --copy -Wno-portability -Wno-portability ...
WARNING: I am going to run configure without any arguments.
Running ./configure --enable-maintainer-mode ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether NLS is requested... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for intltool >= 0.35.0... 0.50.2 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.18.2
checking for XML::Parser... ok
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GNOME_DOC_UTILS... no
checking for MONO_MODULE... no
configure: error: Package requirements (mono >= 2.8.2) were not met:

No package 'mono' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MONO_MODULE_CFLAGS
and MONO_MODULE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Error: Could not run ./configure, which is required to configure banshee-community-extensions

**Comment by BoBeR182** [comment]
sudo apt-get install monodevelop

~/banshee-community-extensions$ ./autogen.sh 
Running intltoolize --force --copy ...
Running libtoolize --force --copy --automake ...
Running aclocal -I build/m4 -I build/m4/shamrock -I build/m4/shave -I build/m4/extensions ...
Running autoconf ...
Running autoheader ...
Running automake --gnu --add-missing --force --copy -Wno-portability -Wno-portability ...
WARNING: I am going to run configure without any arguments.
Running ./configure --enable-maintainer-mode ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking whether NLS is requested... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for intltool >= 0.35.0... 0.50.2 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.18.2
checking for XML::Parser... ok
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GNOME_DOC_UTILS... no
checking for MONO_MODULE... yes
checking for mono... /usr/bin/mono
checking for dmcs... /usr/bin/dmcs
checking for mono... (cached) /usr/bin/mono
checking for xbuild... /usr/bin/xbuild
checking for BANSHEE... no
configure: error: Package requirements (banshee-thickclient >= 2.9.2) were not met:

Package taglib-sharp was not found in the pkg-config search path.
Perhaps you should add the directory containing `taglib-sharp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'taglib-sharp', required by 'Banshee Core', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BANSHEE_CFLAGS
and BANSHEE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Error: Could not run ./configure, which is required to configure banshee-community-extensions

**Comment by BoBeR182** [comment]
git clone git://git.gnome.org/banshee
cd banshee
git clone git://github.com/mono/gtk-sharp.git
cd gtk-sharp
./autogen.sh
make
sudo make install 
cd ..
git clone git@github.com:gstreamer-sharp/gstreamer-sharp
cd gstreamer-sharp
git checkout 1.0
./autogen.sh --prefix=/usr
make
sudo make install 
cd ..
git clone git://github.com/mono/taglib-sharp.git
cd taglib-sharp
./autogen.sh 
make
sudo make install
cd ..

./authgen.sh
make

~/banshee$ make 
Making all in build
Making all in pkg-config
Making all in m4
Making all in data
Making all in audio-profiles
Making all in desktop-files
Found cached translation database
Merging translations into banshee-audiocd.desktop.
Making all in icon-theme-hicolor
Making all in help
Making all in src
Making all in Hyena
Making all in build
Making all in m4
Making all in pkg-config
Making all in Hyena
Making all in Hyena.Data.Sqlite
Making all in Hyena.Gui
Making all in Libraries
Making all in Migo
Making all in Mono.Media
Making all in Mtp
Making all in MusicBrainz
Making all in Lastfm
Making all in Lastfm.Gui
Making all in Core
Making all in Banshee.CollectionIndexer
Making all in Banshee.Core
Making all in Banshee.Services
Making all in Banshee.Widgets
Making all in Banshee.ThickClient
Making all in Banshee.WebBrowser
Making all in libossifer
Making all in Dap
Making all in Banshee.Dap
Making all in Banshee.Dap.AppleDevice
Making all in Banshee.Dap.MassStorage
Making all in Banshee.Dap.Mtp
Making all in Banshee.Dap.Karma
Making all in Extensions
Making all in Banshee.AmazonMp3
Making all in Banshee.AmazonMp3.Store
Making all in Banshee.Audiobook
Making all in Banshee.BooScript
Making all in Banshee.Bpm
Making all in Banshee.CoverArt
Making all in Banshee.Daap
Making all in Banshee.Emusic
Making all in Banshee.Emusic.Store
Making all in Banshee.FileSystemQueue
Making all in Banshee.InternetArchive
Making all in Banshee.Fixup
Making all in Banshee.InternetRadio
Making all in Banshee.Lastfm
Making all in Banshee.LastfmStreaming
Making all in Banshee.LibraryWatcher
Making all in Banshee.MiniMode
Making all in Banshee.Mpris
Making all in Banshee.MiroGuide
Making all in Banshee.MultimediaKeys
Making all in Banshee.NotificationArea
Making all in Banshee.NowPlaying
Making all in Banshee.OpticalDisc
Making all in Banshee.PlayerMigration
Making all in Banshee.PlayQueue
Making all in Banshee.MediaPanel
Making all in Banshee.Podcasting
Making all in Banshee.Sample
Making all in Banshee.SoundMenu
Making all in Banshee.SqlDebugConsole
Making all in Banshee.Torrent
Making all in Banshee.RemoteAudio
Making all in Banshee.UbuntuOneMusicStore
Making all in Banshee.UPnPClient
Making all in Banshee.Wikipedia
Making all in Banshee.YouTube
Making all in Backends
Making all in Banshee.Gio
Making all in Banshee.Gnome
Making all in Banshee.GStreamer
Making all in libbanshee
Making all in Banshee.GStreamerSharp
  MCS   ../../../bin/Banshee.GStreamerSharp.dll
./Banshee.GStreamerSharp/VideoManager.cs(124,58): error CS0266: Cannot implicitly convert type `System.IntPtr' to `ulong'. An explicit conversion exists (are you missing a cast?)
./Banshee.GStreamerSharp/VideoManager.cs(152,54): error CS0266: Cannot implicitly convert type `System.IntPtr' to `ulong'. An explicit conversion exists (are you missing a cast?)
Compilation failed: 2 error(s), 0 warnings
make[4]: *** [../../../bin/Banshee.GStreamerSharp.dll] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by knocte** [comment]
The last error you got is because currently Banshee master branch depends on gstreamer-sharp master branch. I know, this is bad, we should only depend on released versions. We may fix this soon by releasing a new version of gstreamer-sharp.

In general, if you want to contribute a "better how to compile guide", please by any means do, through a pull request. If you just want to bring up an issue, but don't have the guts.. err I mean, the knowledge ;) , then we use bugzilla to record issues: http://bugzilla.gnome.org/ , please record them there. We don't use Github issues.

Therefore, I'm closing this. Welcome to the banshee developer community! :)

**Comment by bl8** [comment]
Hi,
I didn't see that the "Issues" feature could be disabled when moving the repo to GitHub a few weeks ago.
I've now disabled it.
Sorry for the confusion that caused.
